version: '2'
services:
  glassfish:
    build: ../images/glassfish
    ports:
     - "8080:8080"
     - "4848:4848"
  wildfly:
    build: ../images/wildfly
    ports:
     - "9090:8080"
     - "9990:9990"
  tomcat:
    build: ../images/tomcat
    ports:
     - "7070:8080"